/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Onboard_v3RouteImport } from './routes/onboard_v3'
import { Route as IndexRouteImport } from './routes/index'

const Onboard_v3Route = Onboard_v3RouteImport.update({
  id: '/onboard_v3',
  path: '/onboard_v3',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboard_v3': typeof Onboard_v3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboard_v3': typeof Onboard_v3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboard_v3': typeof Onboard_v3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboard_v3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboard_v3'
  id: '__root__' | '/' | '/onboard_v3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Onboard_v3Route: typeof Onboard_v3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard_v3': {
      id: '/onboard_v3'
      path: '/onboard_v3'
      fullPath: '/onboard_v3'
      preLoaderRoute: typeof Onboard_v3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Onboard_v3Route: Onboard_v3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
